apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
    scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 5s
      static_configs:
      - targets: ['localhost:9090']
    - job_name: 'perceptor-scrape'
      scrape_interval: 5s
      static_configs:
      # TODO Add perciever metrics here...
      - targets: ['perceptor:3001', 'perceptor-scanner:3003'] 
