steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o', './cmd/perceptor/perceptor', './cmd/perceptor/perceptor.go']
  env:
  - 'PROJECT_ROOT=github.com/blackducksoftware/perceptor'
  - 'CGO_ENABLED=0'
  - 'GOOS=linux'
  - 'GOARCH=amd64'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/blackducksoftware/perceptor:$BRANCH_NAME', './cmd/perceptor/.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/blackducksoftware/perceptor:$BRANCH_NAME']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    curl -d "" -X POST http://ec2-54-205-198-237.compute-1.amazonaws.com:8081/webhook-perceptor/$REPO_NAME || echo "Success"
