steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o', './cmd/perceptor/perceptor', './cmd/perceptor/perceptor.go']
  env:
  - 'PROJECT_ROOT=github.com/blackducksoftware/perceptor'
  - 'CGO_ENABLED=0'
  - 'GOOS=linux'
  - 'GOARCH=amd64'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/blackducksoftware/perceptor:latest', './cmd/perceptor/.']
images: ['gcr.io/$PROJECT_ID/blackducksoftware/perceptor:latest']
