apiVersion: v1
kind: List
metadata:
  name: "bds-perceptor components"
  resourceVersion: "0.0.1"
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: perceptor
    labels:
      app: perceptor-app
  spec:
    replicas: 1
    selector:
      name: bds-perceptor
    template:
      metadata:
        labels:
          name: bds-perceptor
        name: perceptor
      spec:
        containers:
          - name: perceptor
            image: gcr.io/gke-verification/perceptor:latest
            imagePullPolicy: Always
            command:
              - ./perceptor
            ports:
              - containerPort: 3001
            resources:
              requests:
                memory: 2Gi
                cpu: 50m
              limits:
                cpu: 500m
            volumeMounts:
            - name: perceptor-config
              mountPath: /etc/perceptor
            terminationMessagePath: /dev/termination-log
        volumes:
          - name: perceptor-config
            configMap:
              name: perceptor-config
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
- apiVersion: v1
  kind: Service
  metadata:
    name: perceptor
  spec:
    selector:
      name: bds-perceptor
    ports:
    - nodePort: 0
      port: 3001
      protocol: TCP
      targetPort: 3001
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: perceptor-config
  data:
    perceptor_conf.yaml: |
      HubHost: "nginx-webapp-logstash"
      HubUser: "sysadmin"
      HubUserPassword: "blackduck"
